### ISSUE TITLE
源文档在中文目录下转换失败

### ISSUE THREAD

**Issue by Wickyan** [ystyle/TmdTextEpub#1]
windows版本
源文件（txt格式）如果放在中文目录下，转换到一半就闪退了，换到英文目录就没事
不知道这个Bug能不能复现

**Comment by ystyle** [comment]
没遇到过，我win10和linux都在用， 而且目录结构是 kindle/作者名/书名 都是有中文的。 
你试试: 
- 用打开CMD或powershell
- 输入 `$path/to/TmdTextEpub.exe --filename path/to/txt` 看看日志。 
- 随便说一下其它功能在命令行下用TmdTextEpub.exe -h查看

**Comment by Wickyan** [comment]
我知道了，epub文件正常生成了，mobi文件没有生产
是不是没有检测到有kindlegen.exe?
(程序和源文件放在同一个目录下epub和mobi都能正常生成)


PS：生成的mobi字体是英文字体啊，随然可以用。。但emmmm 能不能优化一下？

**Comment by ystyle** [comment]
1. 如果你喜欢用拖动的方式就把`kindlengen.exe`这文件放 `c:/windows/` 里
如果用命令行的话，把`kindlengen.exe`和 `TmdTextEpub.exe`个文件都扔这里`c:/windows/`
（如果会用添加path的话，自己弄也行）

2. 字体的话, 在kindle是可以切换字体的吧，可以切自定义字体

**Comment by Wickyan** [comment]
确实可以自定义字体，但默认选项是英文的，应该在程序生成mobi的时候有一个语言属性类似于SetLanguage的东西。。。

**Comment by ystyle** [comment]
https://github.com/ystyle/TmdTextEpub/releases/tag/v1.1.9
添加了语言设置选项，和添加额外的kindlengen.exe位置检测
有时间可以试试
