### ISSUE TITLE
安卓最近转换不了

### ISSUE THREAD

**Issue by key147** [ystyle/TmdTextEpub#43]
想问下是不是又换服务器了~

**Comment by ystyle** [comment]
对现在是这个，需要有ipv6，如果wifi没有就切流量数据就好了

wss://kas.ystyle.top:2024/ws



发自我的手机


-------- 原始邮件 --------
发件人： key147 ***@***.***>
日期： 2024年4月24日周三 20:24
收件人： ystyle/kaf-cli ***@***.***>
抄送： Subscribed ***@***.***>
主 题： [ystyle/kaf-cli] 安卓最近转换不了 (Issue #43)

想问下是不是又换服务器了~

―
